server:
  port: 8080
  error:
    include-binding-errors: always
    include-message: always
    include-stacktrace: never
 
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/rest_db
    username: root
    password: insert_password
    driver-class-name: com.mysql.cj.jdbc.Driver
    
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    properties: 
      '[hibernate.format_sql]': true

logging:
  file: 
    name: log/userapp.log 
  pattern: 
    file: "%d %-5level [%thread] %logger:%msg%n" 
  level: 
    '[org.springframework.web]': WARN
    '[org.hibernate]': INFO
    '[com.tpro]': INFO
    
management: # actuator
  endpoints: 
    web: 
      exposure:
        include: ['health', 'loggers', 'env', 'beans']    
    
          
